version: '3.3'
services:
  couchbase:
    image: couchbase/server:5.1.0
    ports:
      - "127.0.0.1:8091:8091" # Admin Web & API, internal access
      - "8092:8092" # , internal access
      - "8093:8093" # user for n1ql query
      - "11210:11210" # DB connection, internal access
    volumes:
      - ./couchbase-db:/opt/couchbase/var
    healthcheck:
      test: ["CMD-SHELL", "cbstats localhost:11210 -b fleet-dev -p 123456 raw warmup | grep -q complete"] # Same password in wrapper > environment > COUCHBASE_PASSWORD and in initialize-db.sh --rbac-password
      interval: 30s
      timeout: 10s
      retries: 50

  sync-gateway:
    build:
      context: sync-gateway
      dockerfile: Dockerfile
    image: sync-gateway:2.0.0
    ports:
      - "4984:4984" # API Rest for Users, open to Web
      - "127.0.0.1:4985:4985" # API Rest Admin, internal access : http://127.0.0.1:4985/_admin/db
    volumes:
      - ./sync-gateway-config.json:/etc/sync_gateway/config.json
    command: -adminInterface :4985 /etc/sync_gateway/config.json
    restart: on-failure # Restart during couchbase warmup
    depends_on:
      - couchbase
